# Makefile - for viTetris
#
# Copyright 2013, Wind River Systems, Inc.
#
# viTetris is terminal based implmetation of the classic tetris game
#  
#
VER=0.57

PKG_URL =  http://www.victornils.net/tetris/vitetris-$(VER).tar.gz

PKG_BUILD_TARGETS = vitetris

PKG_BUILD_DIR = vitetris-$(VER)

PKG_FILE_TYPE = unpack

include $(WIND_KRNL_MK)/rules.unix.ports.mk
